name=input("Enter your name:")
Number=input("Enter your phone number:")
age=input("Enter your age")
age=int(age)
height=input("Enter your height:")
height=float(height)
Eircode=input("Enter your Eircode:")
