num-1#invalid
1num#invalid
firstname#valid
lastname#valid
age#valid
_1#valid
country#valid
city#valid
first_name#valid
last_name#valid
capital_city#valid
year_2021#valid
last-name#invalid
user$name#invalid
year2021#valid
current_year_2021#valid
birth_year#valid
sur@name#invalid
num2#valid
num1#valid